/* web.h generated by valac 0.48.13, the Vala compiler, do not modify */

#ifndef __WEB_H__
#define __WEB_H__

#include <glib.h>
#include <float.h>
#include <math.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <webkit2/webkit2.h>

G_BEGIN_DECLS

#define TYPE_VALA_BROWSER (vala_browser_get_type ())
#define VALA_BROWSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_VALA_BROWSER, ValaBrowser))
#define VALA_BROWSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_VALA_BROWSER, ValaBrowserClass))
#define IS_VALA_BROWSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_VALA_BROWSER))
#define IS_VALA_BROWSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_VALA_BROWSER))
#define VALA_BROWSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_VALA_BROWSER, ValaBrowserClass))

typedef struct _ValaBrowser ValaBrowser;
typedef struct _ValaBrowserClass ValaBrowserClass;
typedef struct _ValaBrowserPrivate ValaBrowserPrivate;

struct _ValaBrowser {
	GtkWindow parent_instance;
	ValaBrowserPrivate * priv;
	gchar* default_protto;
	gchar* default_uri;
	GRegex* protocol_regex;
	GtkToolButton* back_button;
	GtkToolButton* forward_button;
	GtkToolButton* reload_button;
	GtkEntry* url_bar;
	WebKitWebView* web_view;
	GtkLabel* status_bar;
};

struct _ValaBrowserClass {
	GtkWindowClass parent_class;
};

extern gdouble q_tt;
GType vala_browser_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ValaBrowser, g_object_unref)
ValaBrowser* vala_browser_new (void);
ValaBrowser* vala_browser_construct (GType object_type);
void vala_browser_create_widgets (ValaBrowser* self);
void vala_browser_connect_signals (ValaBrowser* self);
void vala_browser_update_buttons (ValaBrowser* self);
void vala_browser_on_activate (ValaBrowser* self);
void vala_browser_start (ValaBrowser* self);
gint vala_browser_main (gchar** args,
                        gint args_length1);

G_END_DECLS

#endif
